[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
inquire = { version = "0.7.5", features = ["date"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
