name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      id: test
      run: cargo test --verbose
      continue-on-error: true
    - name: Create Issue on Test Failure
      if: steps.test.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const runId = context.runId;
          const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;
          
          await github.rest.issues.create({
            owner,
            repo,
            title: `🚨 Tests Failed in Run #${runId}`,
            body: `Tests failed in the latest run. Please check the [workflow run](${runUrl}) for more details.`
          });
